In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
from BabelViscoFDTD.H5pySimple import ReadFromH5py, SaveToH5py
import numpy as np

In [35]:
Skull=ReadFromH5py(r'D:/Shirshak/Research/BabelBrain/Tests/3880\FInalMask.h5')

In [36]:
print(Skull.keys())

dict_keys(['FinalMask'])


In [37]:
unique, counts = np.unique(Skull['FinalMask'], return_counts=True)

In [38]:
print(unique)
print(counts)

[0 2 3 5]
[6035137   90055  390339       1]


In [7]:
# Water['z_vec']*=1e3
Skull['z_vec']*=1e3
Skull['x_vec']*=1e3
Skull['y_vec']*=1e3
Skull['MaterialMap'][Skull['MaterialMap']==3]=2
Skull['MaterialMap'][Skull['MaterialMap']==4]=3

In [28]:
# print(Skull['MaterialMap'].shape)
print(np.argwhere(Skull['FinalMask']==0))
# plt.imshow(Skull['MaterialMap'][10,:,:].T)

[[   0    0    0]
 [   0    0    1]
 [   0    0    2]
 ...
 [ 522 1096  357]
 [ 522 1096  358]
 [ 522 1096  359]]
